language: go
go:
  - 1.14.x
install:
  # Fetch dependencies
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.24.0
  - GO111MODULE=on go mod download
script:
  - ./configure && make test
sudo: false
notifications:
  email: false
